#!/opt/local/bin/perl -w

use strict;
use Finance::QIF;
use Data::Dumper;

my $out = Finance::QIF->new(file => ">-",);
my $header = "Type:Invst";
$out->header($header);

# action matrix
my $action = {
	'Switch In' => "Buy",
	Sale => "Sell",
	'Switch Out' => "Sell",
	'Investment Regular' => "BuyX",
	'Re-registration Transfer In' => "BuyX",
	'Cash Transfer In' => "BuyX",
	'Tax Reclaim Reinvestment' => "ReinvDiv",
	'Dividend Reinvestment' => "ReinvDiv",
	'Investment Lump Sum' => "BuyX",
};

# account matrix dependent on action/description
my $account = {
	'Switch In' => "",
	Sale => "",
	'Switch Out' => "",
	'Investment Regular' => "Investment:Buy",
	'Re-registration Transfer In' => "Investment:Transfer",
	'Cash Transfer In' => "Investment:Transfer",
	'Tax Reclaim Reinvestment' => "Investment:Tax-reclaim",
	#'Dividend Reinvestment' => "Investment:Dividends",
	'Dividend Reinvestment' => "",
	'Investment Lump Sum' => "Investment:Buy",
};

# dispose of header
$_ = <STDIN>;
# data
while (<STDIN>) {
	# strip out currency symbol
	s/,//g;
	# Holding	Date	Description	In (GBP)	Out (GBP)	Price date	Price(p)	Units/Shares	Int charge (GBP)
	#unless (m/([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t\n]+)/) {
	unless (m/([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t]*)\t([^\t\n]+)/) {
#	unless (m/(?:([^\t]*)\t){8}([^\t\n]+)/) {
		print STDERR "Bad record: " . $_;
		next;
	}
	my $record = {
		header => $header,
		security => $1,
		date => $2,
		memo => $3,
		action => $action->{$3},
		account => $account->{$3},
		quantity => $8,
		commission => $9,
	};

	# sort out the cash reserve
	if ($1 eq "Cash Reserve") {
		$record->{price} = 1;
	} else {
		# convert GBP to pence
		$record->{price} = $7 / 100;
	}

	# sort out the transaction amount
	if ($3 eq "Re-registration Transfer In") {
		$record->{amount} = $record->{price} * $record->{quantity};
	} else {
		$record->{amount} = $4 ? $4 : $5;
	}

	# write out the fund transaction
#	print Dumper($record);
	$out->write($record);
}

$out->close;
