#!/opt/local/bin/perl -w

use strict;
use Finance::QIF;
use Data::Dumper;

my $out = Finance::QIF->new(file => ">-",);
my $header = "Type:Invst";
$out->header($header);

my %monthy = ( jan => '01', feb => '02', mar => '03', 
	       apr => '04', may => '05', jun => '06',
	       jul => '07', aug => '08', sep => '09',
	       oct => '10', nov => '11', dec => '12');

# action matrix
my $action = {
	'Switched In' => "Buy",
	'Switched Out' => "Sell",
	'Your single contribution' => "BuyX",
	'Management Charge' => "Sell",
};

# account matrix dependent on action/description
my $account = {
	'Switched In' => "",
	'Switched Out' => "",
	'Your single contribution' => "Investment:Buy",
	'Management Charge' => "",
};

my $lastrecord = undef;

# dispose of header
$_ = <STDIN>;
# data
while (<STDIN>) {
	# strip out currency symbol
	#s/,//g;
# DATE,ACTION,PAYMENTS(£IN),(£OUT),UNIT INVESTMENTS(£),FUND NAME,UNITS(bought),(sold),PRICE PER UNIT(p)
	unless (m/^([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^\n]+)/) {
		print STDERR "Bad record: " . $_;
		next;
	}

	my $record = {
		header => $header,
		security => $6,
		memo => $2 ? $2 : $lastrecord->{memo},
		action => $2 ? $action->{$2} : $lastrecord->{action},
		account => $2 ? $account->{$2} : $lastrecord->{account},
		quantity => $7 ne "0.000" ? $7 : $8,
		price => $9 / 100,
		commission => 0,
	};

	if ($1) {
		$1 =~ /(\d{2})\s+(\w{3})\s+(\d{4})/;
		$record->{date} = $1 . '/' . $monthy{lc($2)} . '/' . $3;
	} else {
		$record->{date} = $lastrecord->{date};
	}

	# sort out the transaction amount
	# better to do this than create a split for multiple management charges
	$record->{amount} = $record->{price} * $record->{quantity};

	# write out the fund transaction
	#print Dumper($record);
	$out->write($record);
	$lastrecord = $record;

	# need a copy to avoid breaking $lastrecord
	if ($record->{memo} eq "Management Charge") {
		my $exprecord = { %$record };
		# need an expense too...
		$exprecord->{action} = 'MiscExp';
		$exprecord->{account} = 'Investment:AMC';
		# write out the expense transaction
#		print Dumper($record);
		$out->write($exprecord);
	}
}

$out->close;
