#!/opt/local/bin/perl -w

use strict;
use Finance::QIF;

my $somefile = 'test.qif';
my $infile = "PruAVCs";

open (IN, "<$infile") or die $!;

my $out = Finance::QIF->new(file => ">" . $somefile,);
my $header = "Type:Invst";
$out->header($header);

my %monthy = ( jan => '01', feb => '02', mar => '03', 
	       apr => '04', may => '05', jun => '06',
	       jul => '07', aug => '08', sep => '09',
	       oct => '10', nov => '11', dec => '12');

# action matrix
my $action = {
	Investment => "BuyX",
	Disinvestment => "Sell",
	Contribution => "BuyX",
	AMC => "MiscExp",
};

# account matrix dependent on action/description
my $account = {
	BuyX => "Salary:Paycheque",
	Sell => "",
	MiscExp => "Investment:AMC",
};

# dispose of header
print $_ = <IN>;
# data
while (<IN>) {
	# strip out currency symbol
	s/£\s*//g;
	unless (m/([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t\n]+)/) {
		print "Bad record: " . $_;
		next;
	}
	my $record = {
		header => $header,
		security => $1,
		memo => $2,
		action => $action->{$4},
		account => $account->{$action->{$4}},
		amount => $6,
		total => $6,
		transaction => $6,
		price => $7,
		quantity => $8,
		commission => 0,
	};
	my $date = $3;
	my $description = $5;

	# translate the date
	$date =~ /(\d{2})\s+(\w{3})\s+(\d{4})/;
	$record->{date} = $3 . '/' . $monthy{lc($2)} . '/' . $1;

	# write out the fund transaction
	$out->write($record);

	if ($description eq "AMC") {
		# need an expense too...
		$record->{action} = $action->{$description};
		$record->{memo} = $description;
		$record->{account} = $account->{$record->{action}};
		# write out the expense transaction
		$out->write($record);
	}
}
$out->close;
close IN;
