#!/opt/local/bin/perl -w

use strict;
use Finance::QIF;

my $somefile = 'test.qif';
my $infile = "PruAVCs";

my %monthy = ( jan => '01', feb => '02', mar => '03', apr => '04', may => '05', jun => '06', jul => '07', 
               aug => '08', sep => '09', oct => '10', nov => '11', dec => '12');

open (IN, "<$infile") or die $!;

my $out = Finance::QIF->new( file => ">" . $somefile, );
my $header = "Type:Invst";
$out->header( $header );

# dispose of header
print $_ = <IN>;
# data
while (<IN>) {
	# strip out currency symbol
	s/£\s*//g;
	unless (m/([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t\n]+)/) {
		print "FAIL: " . $_;
		next;
	}
	my $record = {};

	$record->{header} = $header;
	$record->{security} = $1;
	$record->{memo} = $2;
#	my $status = ($4 eq "Investment" ? "BuyX" : "Sell" );
	my $description = $5;
	$record->{amount} = $record->{total} = $record->{transaction} = $6;
	$record->{price} = $7;
	$record->{quantity} = $8;
	$record->{commission} = 0;

	my $date = $3;

	if ($4 eq "Investment") {
		$record->{action} = "BuyX";
		$record->{account} = 'Salary:Paycheque';
	} else {
		$record->{action} =  "Sell";
	}

	$date =~ /(\d{2})\s+(\w{3})\s+(\d{4})/;
	$record->{date} = $3 . '/' . $monthy{lc($2)} . '/' . $1;

	
#	my $record = {
#	    header      => $header,
#	    date        => $qifdate,
#	    action      => $status,
#	    security    => $security,
#	    price       => $price,
#	    quantity    => $quantity,
##	    status      => $status,
##	    text        => $description,
#	    memo        => $memo,
#	    commission  => $commission,
#	    amount      => $amount,
#	    total       => $amount,
#	    transaction => $amount,
#	    account	=> $account,
#	};
	$out->write($record);

	next unless ($description eq "AMC");
	# need an expense too
#	$record = {
#	    header      => $header,
#	    date        => $qifdate,
#	    action      => 'MiscExp',
#	    memo        => $description,
#	    security    => $security,
#	    price       => $price,
#	    total => $amount,
#	    amount => $amount,
#	    commission => $commission,
#	};
	$record->{action} = 'MiscExp';
	$record->{memo} = $description;
	$record->{account} = 'Investment:AMC';
#	delete $record->{quantity};
	$out->write($record);
}
$out->close;
close IN;
